name: lint
on:
  push:
    branches:
      - main 
  pull_request:

jobs:
  lint:
    name: tsc and eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: yarn
      - name: Fetch Algorithms
        run: yarn fetch-algorithms
      - name: Lint
        run: yarn lint
#      - name: vccrun
#        run: yarn dev

      - name: vccrun
        run: yarn export
       - name: Deploy
       uses: peaceiris/actions-gh-pages@v3
       if: ${{ github.ref == 'refs/heads/main' }}
       with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./out
